CREATE DATABASE miniproject;

DROP TABLE IF EXISTS T_CATEGORY;
CREATE TABLE T_CATEGORY
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS T_PRODUCT;
CREATE TABLE T_PRODUCT
(
    ID              INT(11)      NOT NULL AUTO_INCREMENT,
    NAME            VARCHAR(100) NOT NULL,
    DESCRIPTION     VARCHAR(255) NOT NULL,
    IMAGE           VARCHAR(255) NOT NULL,
    PRICE           BIGINT       NOT NULL,
    STOCK           INT(11)      NOT NULL,
    CATEGORY_ID     BIGINT       DEFAULT 1,
    PRIMARY KEY (ID),
    FOREIGN KEY FK_CATEGORY_PRODUCT (CATEGORY_ID) REFERENCES T_CATEGORY (ID)
);


